<a href="https://colab.research.google.com/github/TokyoGoblin/Algorithm-Development/blob/main/Essential_Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Performing Calculations Using Vectors and Matrixes

In [10]:
import numpy as np
myShort = np.short(15)
myVect = np.array([1, 2, 3, 4])
myVect = np.arange(1, 10, 2)
myVect = np.int16([1, 2, 3, 4])
print(type(myVect[0]))

<class 'numpy.int16'>


In [11]:
 myVect = np.array([1, 2, 3, 4])
 myVect * 1


array([1, 2, 3, 4])

Can perform both logical and comparison tasks with scalar and vector

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

print(a==b)
print(a < b)

[False  True False  True]
[ True False  True False]


In [13]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a))
print(np.logical_xor(a,b))


[ True  True  True False]
[ True False False False]
[False  True False  True]
[False  True  True False]


# Performing Vector Multiplication


An element-by-element multiplication can produce incorrect results when working with algorithms. In many cases, what you really need is a dot product, which is the sum of the products of two number sequences. When working with vectors, the dot product is always the sum of the individual element-by-element multiplications and results in a single number.

In [16]:
#Create a matrix!
myMatrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(myMatrix)
#To access a particular array element, you provide a row and column index value
myMatrix[0,0] #Prints out 1 from the Matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1

Above is a simple matrix and one simple matrix skill. Below is the best way to summon a matrix from the binary depths

In [20]:
myMatrix = np.mat([[1,2,3], [4,5,6], [7,8,9]])
print(type(myMatrix)) #Checks if this is an actual matrix

<class 'numpy.matrix'>


One can also convert an existing array to a matrix using the asmatrix() function. Use the asarray() function to convert a matrix object back to an array form.

Also, the only problem with the matrix class is that it works on only 2-D matrixes.

In [21]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3], [4,5,6]])

print(a*b)

#To perform an element-by-element multiplication, the two matrixes must be the same shape. Otherwise, error message.

[[ 1  4  9]
 [16 25 36]]


In [22]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2,3], [3,4,5], [5,6,7]])

print(a.dot(b))

[[22 28 34]
 [49 64 79]]


In [23]:
changeIt = np.array([1,2,3,4,5,6,7,8])
print(changeIt)

changeIt = changeIt.reshape(2,4)
print(changeIt)

changeIt = changeIt.reshape(2,2,2)
print(changeIt)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
changeIt = np.array([[1,2,3,4],[5,6,7,8]])
print(changeIt)

changeIt = np.transpose(changeIt)
print(changeIt)

print(np.identity(4))  #Identity matrix in numpy, using an identity function
#notice that identity matrix contains all ones on the diagonal

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
a = np.array([[1,2], [3,4]])
b = np.linalg.inv(a)

print(np.allclose(np.dot(a,b), np.identity(2)))

#The output of true tells us that b is the inverse of a.
 #(Sometimes, finding the inverse of a matrix is impossible)
 #When a matrix cannot be inverted, it is a degenerate matrix. (Rare)

True


# Creating Combinations the Right Way

#Shaping data often involves viewing data in multiple ways.

Distinguishing Permutations below

In [28]:
a = np.array([1,2,3])
print(np.random.permutation(a))

#randomizes original data

[2 3 1]


In [29]:
from itertools import permutations

a = np.array([1,2,3])

for p in permutations(a):
  print(p)

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


Shuffling Combinations

In [30]:
from itertools import combinations

a = np.array([1,2,3,4])

for comb in combinations(a,2):
  print(comb)

(1, 2)
(1, 3)
(1, 4)
(2, 3)
(2, 4)
(3, 4)


In [32]:
import random

pool = []

for comb in combinations(a,2):
  pool.append(comb)

print(random.sample(pool,3))  #RANDOMIZE!

[(2, 4), (3, 4), (1, 2)]


Above, the idea is that you've limited your dataset in 2 ways. First, you're not using all the data elements all the time, and second, you're not using all the possible combinations of those data elements. The effect is to create a relatively random-looking set of data elements that you can use as input to an algorithm.

In the Grim Face of Repetition

In [34]:
a = np.array([1,2,3,4,5,6,6,7,7,1,2,3])
b = np.array(list(set(a)))

print(b)

#Repeated data can unfairly weight the output of an algorithm
#so that you get inaccurate results.
#Sommetimes you need unique values to determine the outcome
#of data manipulation.

[1 2 3 4 5 6 7]


In this case above, a begins with an assortment of numbers in no particular order and repeats. In Python, a set never contains repeated data. Consequently, by converting the list in a to a set and then back to a list, and then placing that list in an array, you obtain a vector that has no repeats.

Getting the Desired Results Using Recursion

In [ ]:
#Recursion is an elegant method of solving many computer problems, relying on a capability of a function to continue calling itself until it satisfies a particular condition.
#Main reason to use recursion is that it provides an easier way to solve problems when working with some algorithms because it mimcs the way a human would solve it.
#Recursion is not an easy tool because it requires some effort to understand how to build a recursive routine, and it can cause out-of-memory problems on your computer.

Explaining Recursion

In [36]:
#Simple recursion example: Factorials!!

def factorial(n):
  print("Factorial called with n= ", str(n))
  if n ==1 or n == 0:
    print("Congrats, you did basic math! So proud of you.")
    return 1
  else:
    return n * factorial(n-1)

print(factorial(5))


Factorial called with n=  5
Factorial called with n=  4
Factorial called with n=  3
Factorial called with n=  2
Factorial called with n=  1
Congrats, you did basic math! So proud of you.
120


In [37]:
#Does the same thing as above but with fewer lines of code
def factorial(n):
  print("factorial called with n= ", str(n))
  if n > 1:
    return n * factorial(n-1)
  print("Ending condition met")
  return 1

print(factorial(5))

factorial called with n=  5
factorial called with n=  4
factorial called with n=  3
factorial called with n=  2
factorial called with n=  1
Ending condition met
120


Note the difference above. Instead of checking the ending condition, this version checks the continuation condition. As long as n is greater than 1, the code will continue to make recursive calls. Even though this code is shorter than the previous version, it's also less clear because now you must think about what condition will end the recursion.

ELIMINATING TAIL CALL RECURSION

In [40]:
#A tail call occurs any time the recursion makes a call to the function as the last thing before it returns.
#In the previous section, this was the "return n*factorial(n-1)" bit

#Tail calls are not necessarily bad, and they represent the manner in which most people write recursive routines.
#however, using a tail call forces Python to keep track of the individual call values until the recursion rewinds.
#Each call consumes memory. At some point your system will run out of memory and the call will fail.

#WTIH FANCY PROGRAMMING, WE CAN ELIMINATE TAIL CALLS!

def factorial(n):
  print("factorial called with n=", str(n))
  result = 1
  while n > 1:
    result = result * n
    n = n-1
    print("Current value of n is ", str(n))
  print("Ending condition met.")
  return result

print(factorial(5))


factorial called with n= 5
Current value of n is  4
Current value of n is  3
Current value of n is  2
Current value of n is  1
Ending condition met.
120


# Performing **Tasks** More *Quickly*

Getting tasks done as quickly as possible is ideal. However, you always need to carefully weigh the techniques you use to achieve this effeciency.

**CONSIDERING DIVIDE AND CONQUER** Napoleon time, in short.

In [56]:
#binary search

def search(searchList, key):
  mid = int(len(searchList)/2)
  print("Searching midpoint at ", str(searchList[mid]))

  if mid == 0:
    print("Key Not Found m'lord!")
    return key

  elif key == searchList[mid]:
      print("Key Found sire!")
      return searchList[mid]

  elif key > searchList[mid]:
    print("searchList now contains",
          searchList[mid:len(searchList)])
    search(searchList[mid:len(searchList)], key)

  else:
    print("searchList now contains ",
          searchList[0:mid])
    search(searchList[0:mid], key)

aList = list(range(1,21))  #Remember to indent or you get NOTHING
search(aList, 5)

Searching midpoint at  11
searchList now contains  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Searching midpoint at  6
searchList now contains  [1, 2, 3, 4, 5]
Searching midpoint at  3
searchList now contains [3, 4, 5]
Searching midpoint at  4
searchList now contains [4, 5]
Searching midpoint at  5
Key Found sire!


The list may not contain a search value, so you must always provide an "escape method" for the recursion or the "stack." A stack is a special area of memory used to store the call information. When working with recursion, you must remain proactive or endure the consequences later.

# On the troubling matter of distinguishing between different possible solutions

Recursion is part of many different algorithms programming solutions. It's hard to get away from recursion in many cases because an iterative approach proves nonintuitive, cumbersome, and time consuming. However, you can create a number of different versions of the same solution, each of which has its own characteristics, flaws, and virtues.