<a href="https://colab.research.google.com/github/TokyoGoblin/demon-dungeon/blob/main/Essential_Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Performing Calculations Using Vectors and Matrixes

In [10]:
import numpy as np
myShort = np.short(15)
myVect = np.array([1, 2, 3, 4])
myVect = np.arange(1, 10, 2)
myVect = np.int16([1, 2, 3, 4])
print(type(myVect[0]))

<class 'numpy.int16'>


In [11]:
 myVect = np.array([1, 2, 3, 4])
 myVect * 1


array([1, 2, 3, 4])

Can perform both logical and comparison tasks with scalar and vector

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

print(a==b)
print(a < b)

[False  True False  True]
[ True False  True False]


In [13]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a))
print(np.logical_xor(a,b))


[ True  True  True False]
[ True False False False]
[False  True False  True]
[False  True  True False]


# Performing Vector Multiplication


An element-by-element multiplication can produce incorrect results when working with algorithms. In many cases, what you really need is a dot product, which is the sum of the products of two number sequences. When working with vectors, the dot product is always the sum of the individual element-by-element multiplications and results in a single number.

In [16]:
#Create a matrix!
myMatrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(myMatrix)
#To access a particular array element, you provide a row and column index value
myMatrix[0,0] #Prints out 1 from the Matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1

Above is a simple matrix and one simple matrix skill. Below is the best way to summon a matrix from the binary depths

In [20]:
myMatrix = np.mat([[1,2,3], [4,5,6], [7,8,9]])
print(type(myMatrix)) #Checks if this is an actual matrix

<class 'numpy.matrix'>


One can also convert an existing array to a matrix using the asmatrix() function. Use the asarray() function to convert a matrix object back to an array form.

Also, the only problem with the matrix class is that it works on only 2-D matrixes.

In [21]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3], [4,5,6]])

print(a*b)

#To perform an element-by-element multiplication, the two matrixes must be the same shape. Otherwise, error message.

[[ 1  4  9]
 [16 25 36]]


In [22]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2,3], [3,4,5], [5,6,7]])

print(a.dot(b))

[[22 28 34]
 [49 64 79]]


In [23]:
changeIt = np.array([1,2,3,4,5,6,7,8])
print(changeIt)

changeIt = changeIt.reshape(2,4)
print(changeIt)

changeIt = changeIt.reshape(2,2,2)
print(changeIt)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
changeIt = np.array([[1,2,3,4],[5,6,7,8]])
print(changeIt)

changeIt = np.transpose(changeIt)
print(changeIt)

print(np.identity(4))  #Identity matrix in numpy, using an identity function
#notice that identity matrix contains all ones on the diagonal

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
a = np.array([[1,2], [3,4]])
b = np.linalg.inv(a)

print(np.allclose(np.dot(a,b), np.identity(2)))

#The output of true tells us that b is the inverse of a.
 #(Sometimes, finding the inverse of a matrix is impossible)
 #When a matrix cannot be inverted, it is a degenerate matrix. (Rare)

True


# Creating Combinations the Right Way

#Shaping data often involves viewing data in multiple ways.

Distinguishing Permutations below

In [28]:
a = np.array([1,2,3])
print(np.random.permutation(a))

#randomizes original data

[2 3 1]


In [29]:
from itertools import permutations

a = np.array([1,2,3])

for p in permutations(a):
  print(p)

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


Shuffling Combinations